name: Deployment practice 2
on: push # setting trigger
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci # can also use npm install but npm ci indicates we are using same version as development
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci # can also use npm install but npm ci indicates we are using same version as development
      - name: Test code
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest # on which platform our code should runs on
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci # can also use npm install but npm ci indicates we are using same version as development
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm test # it is a test command of node
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."